name: Url2Image support

on:
  push:
    tags:
      - '*'
  # Cronjob is scheduled for every day at 02:00 PM (Pakistan Standard Time)
  # Equivalent to 08:50 AM UTC
  schedule:
    - cron: "50 08 * * 1-5"  # Runs only Monday to Friday
  workflow_dispatch:  # Allows manual trigger
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check if today is a weekday
        run: |
          DAY_OF_WEEK=$(date +%u)
          if [ "$DAY_OF_WEEK" -gt 5 ]; then
            echo "It's a weekend. Exiting workflow."
            exit 1
          fi

      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Product Hunting
        run: |
          sudo chmod +x daraz.sh && ./daraz.sh
